_extends: probot-settings

repository:
  name: buildkite-asdf-plugin
  description: Use asdf .tool-versions to manage your pipeline's tools
  topics: buildkite, buildkite-plugin

teams:
  - name: infrastructure
    permission: push
