name: Asdf
description: Use asdf .tool-versions to manage your pipeline's tools
author: https://github.com/jessebye
requirements: []
configuration:
  properties:
    path:
      type: string
    tool:
      type: string
  additionalProperties: false
