#!/usr/bin/env bash
set -ueo pipefail

# Text formatting options
bold=$(tput bold)
dim=$(tput dim)
normal=$(tput sgr0)

# Example of getting a plugin parameter:
# myparam=${BUILDKITE_PLUGIN_BUILDKITE_ASDF_PLUGIN_GIT_MYPARAM}

# Assemble Docker arguments
args=(
  "-it" "--rm" "--init"
  "--volume" "${BUILDKITE_BUILD_CHECKOUT_PATH}:/workspace"
  "--volume" "${PLUGIN_DIR}:/plugin"
  "--volume" "/usr/bin/buildkite-agent:/usr/bin/buildkite-agent"
  "--workdir" "/workspace"
  "--env" "BUILDKITE_AGENT_ACCESS_TOKEN"
  "--env" "BUILDKITE_BRANCH"
  "--env" "BUILDKITE_BUILD_ID"
  "--env" "BUILDKITE_JOB_ID"
  "--env" "BUILDKITE_PIPELINE_DEFAULT_BRANCH"
  "alpine:3"
  "/plugin/scripts/run.sh"
)

echo -e "--- :docker: Running script in Docker"
echo -ne "${dim}\$${normal} docker run " >&2

# Print all the arguments, with a space after, properly shell quoted
printf "%q " "${args[@]}"
echo

# Run the script in Docker
docker run "${args[@]}"
