#!/usr/bin/env bash
set -ueo pipefail

ASDF_VERSION="v0.10.0"

if [ ! -f ".tool-versions" ]; then
  echo "No .tool-versions found! Aborting."
  exit 1
fi

echo "--- :git: Cloning asdf"
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch "$ASDF_VERSION" || true

# shellcheck source=/dev/null
. "$HOME"/.asdf/asdf.sh

echo "--- :jigsaw: Installing asdf plugins"
while IFS="" read -r p || [ -n "$p" ]
do
  plugin_name="${p%% *}"
  asdf plugin-add "$plugin_name" || true
done < .tool-versions

echo "--- :toolbox: Installing asdf tool versions"
asdf install

if grep -q nodejs .tool-versions; then
  echo "--- :yarn: Installing yarn"
  npm i -g yarn
fi

export ASDF_DIR
export PATH
